import test from 'node:test';import assert from 'node:assert/strict';
import {Sequencer,canonicalUrl,reactiveEnvelope} from '../public/k-world/audio.js';
const t=n=>({id:n,title:n,url:'https://soundcloud.com/raikouno/'+n,provider:'soundcloud'});
const playlists={gallery:[t('g1'),t('g2')],city:[t('c1'),t('c2')],moon:[t('m1')],same:[t('g1')]};
function setup(){const calls=[],port={load:(t,g)=>calls.push(['load',t.id,g]),play:()=>calls.push(['play']),pause:()=>calls.push(['pause']),seek:n=>calls.push(['seek',n]),rate:()=>false};const s=new Sequencer(port,playlists);s.setZone('gallery');return {s,calls,port};}
function playing(s){s.ready(s.generation,180000);s.playing(s.generation);s.progress(s.generation,50000,180000);}
const loads=c=>c.filter(x=>x[0]==='load');
test('Initial world is silent until armed by a gesture',()=>{const {s,calls}=setup();assert.equal(loads(calls).length,0);s.arm();assert.equal(loads(calls).length,1);});
test('A room change cannot interrupt a playing song',()=>{const {s,calls}=setup();s.arm();playing(s);s.setZone('moon');assert.equal(loads(calls).length,1);assert.equal(s.state.current.id,'g1');assert.equal(s.state.pendingZone,'moon');});
test('Even 99.99 percent progress is not FINISH',()=>{const {s,calls}=setup();s.arm();playing(s);s.progress(s.generation,179999,180000);s.setZone('moon');assert.equal(loads(calls).length,1);});
test('Natural FINISH alone advances to queued room',()=>{const {s,calls}=setup();s.arm();playing(s);s.setZone('moon');assert.equal(s.finish(s.generation),true);assert.equal(loads(calls).length,2);assert.equal(s.state.current.id,'m1');});
test('Rapid crossings collapse to latest destination',()=>{const {s,calls}=setup();s.arm();playing(s);s.setZone('moon');s.setZone('city');assert.equal(s.state.pendingZone,'city');s.finish(s.generation);assert.equal(s.state.current.id,'c1');assert.equal(loads(calls).length,2);});
test('Returning to active room cancels obsolete queued destination',()=>{const {s}=setup();s.arm();playing(s);s.setZone('moon');s.setZone('gallery');assert.equal(s.state.pendingZone,null);s.finish(s.generation);assert.equal(s.state.current.id,'g2');});
test('Repeated zone notifications do not reload',()=>{const {s,calls}=setup();s.arm();playing(s);for(let i=0;i<500;i++)s.setZone('gallery');assert.equal(loads(calls).length,1);});
test('A paused song survives every room change',()=>{const {s,calls}=setup();s.arm();playing(s);s.pause();s.setZone('moon');s.setZone('city');assert.equal(s.state.status,'paused');assert.equal(loads(calls).length,1);assert.equal(s.state.position,50000);});
test('Pause while loading survives a late ready callback',()=>{const {s,calls}=setup();s.arm();s.pause();s.ready(s.generation,180000);assert.equal(s.state.status,'paused');assert.equal(calls.filter(x=>x[0]==='play').length,0);});
test('Late provider PLAY cannot override user pause',()=>{const {s,calls}=setup();s.arm();playing(s);s.pause();const n=calls.length;s.playing(s.generation);assert.equal(calls[n][0],'pause');assert.equal(s.state.status,'paused');});
test('Paused FINISH never auto-resumes',()=>{const {s,calls}=setup();s.arm();playing(s);s.pause();s.setZone('moon');s.finish(s.generation);assert.equal(loads(calls).length,1);assert.equal(s.state.pausedByUser,true);});
test('Manual selection is not replaced by scene routing',()=>{const {s,calls}=setup();s.select(t('manual'));playing(s);s.setZone('moon');s.finish(s.generation);assert.equal(s.state.current.id,'manual');assert.equal(loads(calls).length,1);});
test('Auto on preserves current manual track and queues location',()=>{const {s,calls}=setup();s.select(t('manual'));playing(s);s.setZone('moon');s.auto(true);assert.equal(loads(calls).length,1);assert.equal(s.state.pendingZone,'moon');});
test('Auto on does not erase pause intent',()=>{const {s,calls}=setup();s.select(t('manual'));playing(s);s.pause();s.setZone('moon');s.auto(true);assert.equal(s.state.pausedByUser,true);assert.equal(loads(calls).length,1);});
test('Duplicate or stale FINISH cannot skip another song',()=>{const {s,calls}=setup();s.arm();playing(s);const old=s.generation;s.setZone('moon');s.finish(old);s.finish(old);s.finish(s.generation);assert.equal(loads(calls).length,2);});
test('Stale ready/progress/error callbacks are ignored',()=>{const {s}=setup();s.arm();const old=s.generation;s.select(t('manual'));s.ready(old,9999);s.progress(old,1000,9999);s.fail(old,'stale');assert.equal(s.state.duration,0);assert.equal(s.state.error,null);assert.equal(s.state.status,'loading');});
test('Loading song remains protected when scene changes',()=>{const {s,calls}=setup();s.arm();s.setZone('city');assert.equal(loads(calls).length,1);assert.equal(s.state.pendingZone,'city');});
test('Single-song playlist can replay after completion',()=>{const {s,calls}=setup();s.setZone('moon');s.arm();playing(s);s.finish(s.generation);assert.equal(loads(calls).length,2);assert.equal(s.state.current.id,'m1');});
test('Provider errors do not silently skip or retry-loop',()=>{const {s,calls}=setup();s.arm();s.fail(s.generation,'offline');for(let i=0;i<50;i++)s.setZone('moon');assert.equal(loads(calls).length,1);assert.equal(s.state.status,'error');});
test('Explicit skip is a deliberate exception',()=>{const {s,calls}=setup();s.arm();playing(s);s.setZone('moon');s.skip();assert.equal(loads(calls).length,2);assert.equal(s.state.current.id,'m1');});
test('Volume does not reload current song',()=>{const {s,calls}=setup();s.arm();playing(s);s.volume(20);assert.equal(loads(calls).length,1);assert.equal(s.state.volume,20);});
test('Unsupported provider speed does not claim success',()=>{const {s}=setup();s.arm();assert.equal(s.rate(1.5),false);assert.equal(s.state.rate,1);});
test('Reject malformed and non-SoundCloud URLs',()=>{for(const url of ['javascript:alert(1)','https://soundcloud.com.evil.test/a/b','http://soundcloud.com/a/b','https://soundcloud.com/a','https://soundcloud.com/a/sets/foo'])assert.equal(canonicalUrl(url),null);assert.equal(canonicalUrl('https://soundcloud.com/raikouno/hot-sauce-mp3?in=a/b'),'https://soundcloud.com/raikouno/hot-sauce-mp3');});
test('Paused reactive envelope is zero and never fake FFT',()=>{assert.deepEqual(reactiveEnvelope({status:'paused',position:3000}),{bass:0,mid:0,high:0,energy:0,source:'clock'});assert.equal(reactiveEnvelope({status:'playing',position:3000}).source,'clock');assert.equal(reactiveEnvelope({status:'playing',position:3000},{bass:.1,mid:.2,high:.3,source:'pcm'}).source,'pcm');});

test('Changing from local audio to SoundCloud resets actual rate display to 1x',()=>{const {s,port}=setup();port.rate=()=>true;s.select({...t('local'),provider:'local'});s.rate(1.25);assert.equal(s.state.rate,1.25);s.select(t('remote'));assert.equal(s.state.rate,1);});
test('Local-to-local playback preserves a valid speed preference',()=>{const {s,port}=setup();port.rate=()=>true;s.select({...t('local-one'),provider:'local'});s.rate(.8);s.select({...t('local-two'),provider:'local'});assert.equal(s.state.rate,.8);});
