import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {buildScene,isFree,moveCamera} from '../public/k-world/scenes.js';import {ART,WORLDS} from '../public/k-world/data.js';import {iconFrame} from '../public/k-world/icons.js';
const manifest=JSON.parse(fs.readFileSync(new URL('../public/k-world/assets/manifest.json',import.meta.url)));
const assets={images:new Map(manifest.map(m=>[m.id,{naturalWidth:m.width,naturalHeight:m.height}])),label:()=> 'label',ornament:()=> 'ornament',skyTexture:()=> 'sky',material:()=> 'material',floorTexture:()=> 'floor'};
const scenes=new Map(['gallery','city',...WORLDS.map(w=>w.id)].map(id=>[id,buildScene(assets,id)]));
test('All 13 supplied art and band assets have exact SHA-256 manifests',()=>{assert.equal(manifest.length,13);for(const m of manifest){const bytes=fs.readFileSync(new URL('../public/k-world/assets/'+m.file,import.meta.url));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),m.sha256);assert(m.width>100&&m.height>100);}});
test('Twelve individual artworks are modeled as inspectable physical frames',()=>{const art=scenes.get('gallery').interactions.filter(t=>t.type==='art');assert.equal(art.length,12);assert.deepEqual(art.map(x=>x.art),ART.map(x=>x.id));});
for(const [id,scene] of scenes){
 test(`${id}: unique finite geometry and collision-free spawn`,()=>{assert(scene.meshes.length>3);for(const m of scene.meshes)assert(m.data.every(Number.isFinite));assert(isFree(scene,scene.spawn[0],scene.spawn[2],.28,scene.spawn[1]));});
 test(`${id}: every door / artwork is reachable from spawn`,()=>{const step=.5,[minX,maxX,minZ,maxZ]=scene.bounds,key=(x,z)=>x+':'+z,start=[Math.round(scene.spawn[0]/step)*step,Math.round(scene.spawn[2]/step)*step],todo=[start],visited=new Set([key(...start)]);for(let i=0;i<todo.length;i++){const [x,z]=todo[i];for(const [dx,dz] of [[step,0],[-step,0],[0,step],[0,-step]]){const nx=x+dx,nz=z+dz,k=key(nx,nz);if(nx<minX||nx>maxX||nz<minZ||nz>maxZ||visited.has(k)||!isFree(scene,nx,nz,.29,1.7))continue;visited.add(k);todo.push([nx,nz]);}}for(const obj of scene.interactions)assert(todo.some(([x,z])=>Math.hypot(x-obj.position[0],z-obj.position[2])<obj.radius-.05),obj.id+' unreachable');});
}
test('All six realms return to actual K City',()=>{for(const w of WORLDS)assert(scenes.get(w.id).interactions.some(t=>t.to==='city'));assert(scenes.get('city').interactions.some(t=>t.to==='gallery'));});
test('Movement cannot tunnel through collision at large dt',()=>{const g=scenes.get('gallery'),camera={position:[0,1.7,0]};moveCamera(g,camera,-100,0);assert(camera.position[0]>-12);assert(isFree(g,camera.position[0],camera.position[2],.28,1.7));});
test('Worlds are independent mesh and collision collections',()=>{const all=[...scenes.values()];for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){assert.notEqual(all[i].meshes,all[j].meshes);assert.notEqual(all[i].colliders,all[j].colliders);}});
test('Every portal has a bounded animated ASCII projection',()=>{for(const w of WORLDS){const first=iconFrame(w.icon,0),next=iconFrame(w.icon,2);assert.equal(first.split('\n').length,22);assert(first.split('\n').every(l=>l.length===48));assert.notEqual(first,next);}});
