import { Link } from 'react-router-dom';

type Packet = {
  title:string; eyebrow:string; status:string; state:string; thesis:string; problem:string; constraints:string[];
  architecture:{title:string;body:string}[]; evidence:string[]; verification:string[]; result:string; limitation:string; primitives:string[]; source?:string; meta?:string;
};

const packets:Record<string,Packet> = {
  residual: {
    title:'RESIDUAL', eyebrow:'AI RELIABILITY / PLATFORM ENGINEERING / APPLIED R&D', status:'PUBLIC R&D · ACTIVE', state:'IMPLEMENTED / ACTIVE EVALUATION', meta:'2026 · CURRENT GENERATION: FACTORY / STUDIO', source:'https://github.com/ninja-ops-guy/residual-agent-harness',
    thesis:'I am testing a systems-level hypothesis: AI reliability does not necessarily require making each individual model reliable. RESIDUAL treats model output as an untrusted proposal and moves authority into the surrounding system: constrain the worker, observe what happened, verify the result independently, and integrate only accepted state.',
    problem:'Most agent systems put too much trust inside the worker. More context, tools, retries, or autonomy can make a model more capable without making its effects trustworthy. I wanted a control layer where weak or strong, local or cloud, deterministic or stochastic workers can fail without silently turning failure into accepted state.',
    constraints:['Workers propose; verifiers decide','UNKNOWN is never silently converted to PASS','Contracts, scope, tools, resources, dependencies, evidence, and checks are explicit before execution','Stochastic workers do not get unilateral authority over accepted state','Human approval is durable, auditable, and protected against replay','Parallelism must justify its coordination, verification, and integration cost'],
    architecture:[
      {title:'01 / Requirement → frozen plan',body:'Intent becomes explicit obligations, dependencies, contracts, evidence requirements, and acceptance checks before workers are given authority.'},
      {title:'02 / Router + scheduler',body:'The system selects direct, verified, swarm, ensemble, local, or remote execution using policy, capability, observed performance, cost, and orchestration tax.'},
      {title:'03 / Bounded workers',body:'Workers operate as untrusted computation inside explicit contracts and isolated workspaces. They produce candidate artifacts and observations, not accepted truth.'},
      {title:'04 / Evidence fabric',body:'Observations, artifacts, hashes, provenance, verifier revisions, dependencies, and outcomes survive handoffs as inspectable evidence and receipts.'},
      {title:'05 / Independent verification',body:'Candidate work is checked outside the worker. PASS, FAIL, UNKNOWN, SKIPPED, malformed output, provider errors, and verifier exceptions remain distinct outcomes.'},
      {title:'06 / Deterministic integration',body:'Only verified work crosses the acceptance boundary. FAIL or UNKNOWN becomes a counterexample or residual packet for repair, escalation, or human review.'},
    ],
    evidence:['Obligation DAGs, immutable evidence snapshots, verifier-defined acceptance, counterexample-directed repair, and residual delegation','Frozen Factory execution plans, bounded worker contracts, isolated worktrees, evidence plumbing, and deterministic integration primitives','Schema-versioned receipts and verifier revisions binding accepted artifacts to evidence, policy, dependencies, and verifier identity','Durable HITL state with replay prevention plus explicit fail-closed handling for negative and uncertain verification','Adaptive assurance and verifier-quality profiles so the quality of the checking layer is itself measurable','Learned orchestration-tax estimates and heterogeneous engine routing so parallelism and compute selection are engineering decisions rather than assumptions','Command Station operator surface plus Factory / Studio execution path for self-hosted local/cloud operation'],
    verification:['Automated tests exercise contracts, receipt graphs, verifier identity, HITL replay prevention, routing boundaries, deterministic integration, recovery, and platform behavior','Factory CI preserves exact source, Git tree identity, and test output so qualification evidence can be tied to the code that produced it','The research program separates implemented mechanisms from the larger reliability claim and defines paired trials, ablations, fault injection, model-degradation studies, hidden grading, and matched baselines','Acceptance authority remains outside the model: model confidence, provider choice, or a worker self-report cannot independently turn a candidate into accepted state'],
    result:'RESIDUAL has become more than an agent workflow. It is a reusable control architecture for running unreliable computation under explicit authority boundaries: contracts, evidence, independent verification, deterministic integration, routing, adaptive assurance, durable state, and human escalation.',
    limitation:'The architecture is implemented and actively tested, but the broad research hypothesis is not claimed as proven. External workloads, independent operators, controlled baselines, verifier-quality measurement, and statistically disciplined evaluation still determine how far the reliability claim can go.',
    primitives:['Frozen execution contracts','Evidence fabric + receipts','Verifier revisions','Deterministic integrator','Residual escalation','Adaptive assurance','Verifier-quality profiles','Orchestration tax','Durable HITL','Heterogeneous compute routing']
  },
  'verified-cyber-planning': {
    title:'Verified Cyber Planning', eyebrow:'SECURITY RESEARCH / FORMAL REASONING', status:'RESEARCH PROGRAM · PRIVATE', state:'INTERNALLY BENCHMARKED',
    thesis:'I wanted to know whether a generated cyber plan could be treated like an engineering artifact: checked, rejected, explained, and replanned against explicit rules instead of trusted because the planner said it was good.',
    problem:'Automated planning is only useful to me if the result can be checked against scope, preconditions, policy, timing, and evidence requirements. The interesting problem is not just generating a plan. It is making plan acceptance independently verifiable.',
    constraints:['Operate only inside explicit rules of engagement and bounded lab/CTF scopes','Separate plan generation from plan acceptance','Return useful counterevidence when a plan is invalid','Preserve provenance so later replanning can explain why a decision changed'],
    architecture:[{title:'Planning portfolio',body:'A*, SAT, incremental, and hierarchical planners can compete while using a shared intermediate representation.'},{title:'SAT/SMT verification',body:'Plans are checked against formalized constraints, policy objects, preconditions, temporal rules, and evidence requirements.'},{title:'Counterexamples',body:'When a plan fails, unsatisfied cores and counterexamples show why instead of returning a useless boolean.'},{title:'Research harness',body:'CyberPlanBench, digital-twin scenarios, stochastic campaigns, mutation/replanning, and audit artifacts give me repeatable ways to compare behavior.'}],
    evidence:['SAT/SMT plan verifier and plan-proof artifacts','MUS/counterexample generation for rejected constraints','Cyber IR / policy objects and temporal rule handling','Multiple planner strategies with replanning and cache behavior','Benchmark and challenge-pack infrastructure retained as inspectable research artifacts'],
    verification:['Planner output is checked by a separate verifier instead of being accepted by self-report','Policy and scope failures become explicit rejection evidence','Counterfactual and replanning paths go through the same acceptance boundary'],
    result:'The most useful thing that came out of the project is not one planner. It is the verification layer around planning: policy objects, plan proofs, counterexamples, evidence contracts, and a benchmark surface for comparing strategies.',
    limitation:'This is bounded ethical-security research. It is not evidence that autonomous planning is ready for unrestricted real-world offensive use. External validation and broader benchmark diversity are still open work.',
    primitives:['Verified planners','Cyber IR','Policy objects','Plan proofs','MUS counterexamples','Replanning contracts','CyberPlanBench']
  }
};

const box={border:'1px solid #162235',background:'rgba(8,15,28,.78)'};
const flow=['REQUIREMENT','FROZEN CONTRACT','ROUTER / SCHEDULER','BOUNDED WORKERS','EVIDENCE FABRIC','VERIFIERS','DETERMINISTIC INTEGRATOR','RECEIPT'];

export default function ProgramCaseStudy({slug}:{slug:string}){
  const p=packets[slug]; if(!p) return null;
  return <main style={{minHeight:'100vh',background:'#050A14',color:'#E8EDF3'}}><div className="max-w-[1080px] mx-auto px-6 md:px-10" style={{paddingTop:72,paddingBottom:120}}>
    <Link to="/#work" className="font-label" style={{color:'#8899AA'}}>← PORTFOLIO</Link>
    <header style={{marginTop:70}}><p className="font-label" style={{color:'#4A6DFF'}}>{p.eyebrow}</p><h1 className="font-headline" style={{fontSize:'clamp(3rem,8vw,6.4rem)',lineHeight:.92,letterSpacing:'-.04em',marginTop:18}}>{p.title}</h1><div className="flex flex-wrap gap-2" style={{marginTop:24}}><span className="font-label" style={{color:'#9AAEFF'}}>● {p.status}</span><span className="font-label" style={{border:'1px solid #334766',background:'rgba(74,109,255,.12)',padding:'7px 9px',color:'#9AAEFF'}}>{p.state}</span>{p.meta&&<span className="font-label" style={{border:'1px solid #263750',padding:'7px 9px',color:'#718399'}}>{p.meta}</span>}</div><p className="font-body" style={{color:'#A6B3C2',fontSize:20,lineHeight:1.65,maxWidth:850,marginTop:28}}>{p.thesis}</p>{p.source&&<a href={p.source} target="_blank" rel="noreferrer" className="font-label inline-block" style={{color:'#7DE2A8',marginTop:22,border:'1px solid #315B47',padding:'10px 13px'}}>VIEW SOURCE / EVIDENCE ↗</a>}</header>
    {slug==='residual'&&<section style={{marginTop:72}}><p className="font-label" style={{color:'#4A6DFF'}}>CONTROL LOOP / AUTHORITY BOUNDARY</p><div className="flex flex-wrap items-center gap-2" style={{...box,marginTop:20,padding:24}}>{flow.map((x,i)=><span key={x} className="flex items-center gap-2"><span className="font-label" style={{border:'1px solid #334766',padding:'10px 12px',color:i>=5?'#7DE2A8':'#A9B6C5'}}>{x}</span>{i<flow.length-1&&<span style={{color:'#4A6DFF'}}>→</span>}</span>)}</div><p className="font-body" style={{color:'#718399',fontSize:13,lineHeight:1.7,marginTop:12}}>FAIL / UNKNOWN does not cross the acceptance boundary. It becomes counterevidence, a residual packet, retry, escalation, or human review.</p></section>}
    <section style={{marginTop:88}}><p className="font-label" style={{color:'#4A6DFF'}}>01 / WHAT I WAS TRYING TO SOLVE</p><p className="font-body" style={{fontSize:17,color:'#B7C3D0',lineHeight:1.8,marginTop:18}}>{p.problem}</p></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#4A6DFF'}}>02 / RULES I WOULD NOT BREAK</p><div style={{...box,marginTop:22,padding:24}}>{p.constraints.map(x=><p key={x} className="font-body" style={{color:'#A9B6C5',lineHeight:1.7,margin:'8px 0'}}>→ {x}</p>)}</div></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#4A6DFF'}}>03 / HOW I BUILT IT</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{marginTop:22}}>{p.architecture.map(x=><div key={x.title} className="p-6" style={box}><h3 className="font-headline" style={{fontSize:22}}>{x.title}</h3><p className="font-body" style={{color:'#9EADBD',lineHeight:1.7,marginTop:12}}>{x.body}</p></div>)}</div></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#4A6DFF'}}>04 / WHAT I CAN POINT TO</p><div style={{...box,marginTop:22,padding:26}}>{p.evidence.map((x,i)=><p key={x} className="font-body" style={{color:'#B7C3D0',lineHeight:1.75,borderBottom:i<p.evidence.length-1?'1px solid #162235':undefined,padding:'11px 0'}}>0{i+1} — {x}</p>)}</div></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#4A6DFF'}}>05 / HOW I CHECKED IT</p><div style={{marginTop:18}}>{p.verification.map(x=><p key={x} className="font-body" style={{color:'#A6B3C2',lineHeight:1.75,padding:'10px 0',borderBottom:'1px solid #162235'}}>→ {x}</p>)}</div></section>
    <section className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{marginTop:78}}><div className="p-6" style={box}><p className="font-label" style={{color:'#7DE2A8'}}>WHAT I GOT OUT OF IT</p><p className="font-body" style={{color:'#B7C3D0',lineHeight:1.75,marginTop:14}}>{p.result}</p></div><div className="p-6" style={box}><p className="font-label" style={{color:'#D8B26E'}}>WHAT IS STILL OPEN</p><p className="font-body" style={{color:'#B7C3D0',lineHeight:1.75,marginTop:14}}>{p.limitation}</p></div></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#4A6DFF'}}>06 / WHAT I CAN REUSE</p><div className="flex flex-wrap gap-2" style={{marginTop:20}}>{p.primitives.map(x=><span key={x} className="font-label" style={{border:'1px solid #263750',padding:'9px 11px',color:'#A9B6C5'}}>{x}</span>)}</div></section>
  </div></main>;
}
