import { Link } from 'react-router-dom';
import EvidenceExplorer, { type EvidenceItem } from '../components/EvidenceExplorer';

type Packet = {
  title:string; eyebrow:string; status:string; state:string; thesis:string; problem:string; constraints:string[];
  architecture:{title:string;body:string}[]; evidence:string[]; verification:string[]; result:string; limitation:string; primitives:string[];
  integrations?:{title:string;body:string}[]; roadmap?:string[]; ideas?:{title:string;body:string}[]; impact?:string;
};

const packets:Record<string,Packet> = {
  residual: {
    title:'RESIDUAL', eyebrow:'AI SYSTEMS / VERIFICATION / AGENT INFRASTRUCTURE', status:'ACTIVE R&D · PUBLIC', state:'IMPLEMENTED CORE / ACTIVE QUALIFICATION',
    thesis:'I started RESIDUAL because I kept coming back to the same problem: AI agents can be useful even when the models underneath them are inconsistent. Instead of trying to pretend that inconsistency does not exist, I wanted to build the system around it.',
    problem:'The deeper I got into agent workflows, the less interested I became in another demo where an AI writes code and then tells me it worked. The real question was what happens after the model responds. What was it allowed to touch? What evidence did it produce? Who decides whether the result is actually good enough? What happens when a verifier says no, the provider fails, the model runs out of budget, or two workers disagree? RESIDUAL grew out of trying to make those boundaries explicit, testable, and hard to bypass.',
    constraints:['Workers can propose changes, but they do not own acceptance authority','Negative, unknown, blocked, and malformed results stay visible instead of being converted into success','Evidence has to remain bound to the exact artifact, verifier, policy, revision, and parent lineage that produced it','Provider choice, model confidence, and agent self-report cannot bypass verification','Human approval has to be durable, explicit, and resistant to replay','Research claims stay narrower than the evidence that actually supports them'],
    architecture:[
      {title:'Core harness',body:'The harness turns a mission into explicit obligations, budgets, checks, evidence, and acceptance rules. The model is a worker inside that process, not the authority over it.'},
      {title:'Command Station / Mission Control',body:'I built an operator surface for launching work, watching what agents are doing, managing providers, inspecting evidence, escalating to a human, and working with isolated browser or guest environments.'},
      {title:'Factory runtime',body:'M2/M3/M4 add bounded worker contracts, an evidence bus with receipts, and deterministic scheduling/integration. The goal is to make a swarm behave more like a controlled distributed system than a group chat.'},
      {title:'Verification + receipts',body:'Accepted output carries evidence about what was checked, under which verifier and revision, and against which contract. A receipt is not a claim of universal truth; it is a record of exactly what passed.'},
      {title:'Fail-closed control',body:'Workers can fail, providers can fail, and experiments can fail without silently becoming accepted state. That sounds obvious, but stress testing has already found places where authority ordering needed to be tightened.'},
      {title:'Evaluation layer',body:'I use frozen workloads, fault injection, heterogeneous local-model runs, ablations, and retained PASS/FAIL/BLOCKED/UNKNOWN outcomes so the research can be challenged instead of just demonstrated.'},
    ],
    integrations:[
      {title:'Local + cloud models',body:'RESIDUAL is intentionally model-agnostic. Local Ollama workers, cloud models, and OpenAI-compatible endpoints can be routed for different jobs without giving any provider special authority over acceptance.'},
      {title:'Agent frameworks',body:'LangGraph, CrewAI, SDK-driven workers, and custom runtimes can sit behind the same boundary. I would rather wrap useful ecosystems with evidence and verification than rebuild every orchestration feature myself.'},
      {title:'Enterprise agent platforms',body:'I am exploring how the same control layer can sit behind tools such as Copilot Studio, where identity, connectors, and department-specific agents already exist. RESIDUAL would focus on the assurance boundary around higher-impact engineering work.'},
      {title:'Robotics / WirePod',body:'One of the directions I care about most is using RESIDUAL with my Vector / wire-pod work. Instead of an LLM going directly from intent to robot action, a new behavior can be generated, checked against a contract, tested, receipted, and only then exposed to the robot.'},
      {title:'Security research',body:'The same architecture maps naturally onto red-team and defensive workflows: agents can investigate, generate tooling, or propose actions while execution, evidence, and acceptance stay independently controlled.'},
      {title:'Disposable execution',body:'Mission Control and WebVM work let me explore the pattern of executing AI-generated work in a disposable environment, capturing what happened, and only allowing verified artifacts to cross the boundary.'},
    ],
    evidence:['Core harness, Command Station, Mission Control / WebVM, and Factory M2/M3/M4 are implemented','Worker contracts, evidence receipts, deterministic integration, provider routing, durable HITL, and bounded execution exist as real code paths','Engine adapters cover LangGraph, CrewAI, SDK-style execution, and isolated-process workers','A heterogeneous local-model DAG experiment retained both an earlier FAIL and a later bounded 3/3 PASS rather than erasing the negative result','M6 self-maintenance experiments have repeatedly failed within the frozen pass budget and are retained as negative evidence','Stress campaigns exposed concrete authority-ordering defects around budget accounting and release eligibility, which now drive repair and requalification work','The project explicitly distinguishes implementation presence from production or scientific qualification'],
    verification:['Automated tests exercise contracts, receipts, verifier identity, routing boundaries, HITL replay prevention, and Factory integration','Stress campaigns deliberately inject malformed output, verifier denial, repair pressure, provider failure, and accounting edge cases','Research results are revision-bound, and a later PASS does not invalidate or overwrite an earlier FAIL','Acceptance stays separate from model confidence, provider output, workflow exit status, or the fact that code exists','Current production-readiness work includes blank-environment installation, recovery/host-loss qualification, soak testing, live-provider evidence, and mobile/WebVM reliability rather than treating green CI as the whole story'],
    roadmap:[
      'Finish the current qualification work: authority ordering, release eligibility, install/recovery, soak, live-provider, and physical-device evidence',
      'Keep expanding Factory into a stronger heterogeneous local/cloud execution plane with cost- and capability-aware routing',
      'Push Mission Control toward a practical operator console for distributed workflows, evidence inspection, and intervention',
      'Continue M6 as bounded research: frozen improvement hypotheses, generated candidates, independent experiments, retained evidence, and no autonomous merge authority',
      'Use RESIDUAL as an external assurance layer for my red-team harness, enterprise agent experiments, and robotics work',
      'Explore governed dynamic behavior generation for Vector, where new skills can be proposed and qualified through repeated observe-orient-decide-act loops',
      'Move toward an evidence-preserving self-healing system that can diagnose, repair, requalify, and still retain the original failure as part of the record',
    ],
    ideas:[
      {title:'Reliability from architecture',body:'The biggest hypothesis is that useful AI reliability may come from the system around the model: constraints, redundancy, observation, verification, deterministic control, and recovery. I do not need every worker to be perfect if the architecture assumes they are not.'},
      {title:'Generation is not authority',body:'The component that creates an answer should not automatically decide whether that answer becomes reality. Separating generation from verification and integration is the security property I care about most.'},
      {title:'Evidence as an output',body:'I want an AI engineering system to produce more than a result. It should also produce enough provenance, execution evidence, and acceptance context for someone else to understand why that result was allowed through.'},
      {title:'Receipts over confidence',body:'Model confidence is interesting, but it is not the same thing as verification. A receipt can say exactly what was checked, by what revision, under which policy, and with which evidence.'},
      {title:'Controlled recursive improvement',body:'If M6 eventually works, the interesting result is not “AI rewrites itself.” It is a system that can identify a weakness, freeze a hypothesis, generate a repair, test it, independently verify it, retain failure, and only promote what survives.'},
      {title:'Agents as heterogeneous compute',body:'I think swarms are more interesting when models are treated as different compute resources rather than personalities in a chat room. Cheap local models, stronger cloud models, deterministic tests, specialized verifiers, and humans can each do the part they are best at.'},
    ],
    result:'What I have gotten out of RESIDUAL so far is bigger than a coding agent. I now have a reusable way to think about autonomous systems: untrusted workers inside explicit contracts, evidence that survives the run, independent verification, deterministic integration, and human authority at the edge. Just as importantly, the project has already found its own flaws. Failed M6 trials and stress campaigns have exposed real weaknesses instead of being hidden behind a demo. That is the outcome I care about right now: a system that is becoming more trustworthy because it can preserve and learn from evidence that says “this did not work.”',
    limitation:'RESIDUAL is not a finished autonomous engineer, a universal proof system, or evidence that recursive self-improvement is solved. Production qualification is still incomplete in several areas, the strongest M6 claims are explicitly unproven, and some integrations are research directions rather than shipped product capabilities. I consider that boundary part of the work, not a footnote.',
    primitives:['Execution contracts','Evidence receipts','Verifier-bound acceptance','Deterministic integration','Durable HITL','Heterogeneous model routing','Fail-closed governance','Obligation DAGs','Quarantine boundaries','Frozen experiments','Evidence-preserving repair'],
    impact:'If the architecture holds up, the impact I care about is not simply “better AI coding.” It is making increasingly autonomous systems easier to inspect, govern, challenge, and trust in software engineering, cybersecurity, enterprise automation, robotics, and research. The long-term outcome would be a platform where humans can use large networks of local, cloud, specialized, and physical AI workers without handing any one model unconditional authority.'
  },
  'verified-cyber-planning': {
    title:'Verified Cyber Planning', eyebrow:'SECURITY RESEARCH / FORMAL REASONING', status:'RESEARCH PROGRAM · PRIVATE', state:'INTERNALLY BENCHMARKED',
    thesis:'I wanted to know whether a generated cyber plan could be treated like an engineering artifact: checked, rejected, explained, and replanned against explicit rules instead of trusted because the planner said it was good.',
    problem:'Automated planning is only useful to me if the result can be checked against scope, preconditions, policy, timing, and evidence requirements. The interesting problem is not just generating a plan. It is making plan acceptance independently verifiable.',
    constraints:['Operate only inside explicit rules of engagement and bounded lab/CTF scopes','Separate plan generation from plan acceptance','Return useful counterevidence when a plan is invalid','Preserve provenance so later replanning can explain why a decision changed'],
    architecture:[
      {title:'Planning portfolio',body:'A*, SAT, incremental, and hierarchical planners can compete while using a shared intermediate representation.'},
      {title:'SAT/SMT verification',body:'Plans are checked against formalized constraints, policy objects, preconditions, temporal rules, and evidence requirements.'},
      {title:'Counterexamples',body:'When a plan fails, unsatisfied cores and counterexamples show why instead of returning a useless boolean.'},
      {title:'Research harness',body:'CyberPlanBench, digital-twin scenarios, stochastic campaigns, mutation/replanning, and audit artifacts give me repeatable ways to compare behavior.'},
    ],
    evidence:['SAT/SMT plan verifier and plan-proof artifacts','MUS/counterexample generation for rejected constraints','Cyber IR / policy objects and temporal rule handling','Multiple planner strategies with replanning and cache behavior','Benchmark and challenge-pack infrastructure retained as inspectable research artifacts'],
    verification:['Planner output is checked by a separate verifier instead of being accepted by self-report','Policy and scope failures become explicit rejection evidence','Counterfactual and replanning paths go through the same acceptance boundary'],
    result:'The most useful thing that came out of the project is not one planner. It is the verification layer around planning: policy objects, plan proofs, counterexamples, evidence contracts, and a benchmark surface for comparing strategies.',
    limitation:'This is bounded ethical-security research. It is not evidence that autonomous planning is ready for unrestricted real-world offensive use. External validation and broader benchmark diversity are still open work.',
    primitives:['Verified planners','Cyber IR','Policy objects','Plan proofs','MUS counterexamples','Replanning contracts','CyberPlanBench']
  }
};

const residualAudit:EvidenceItem[]=[
  {label:'Source repository',state:'IMPLEMENTED',summary:'Public implementation and revision history for the harness.',href:'https://github.com/ninja-ops-guy/residual-agent-harness',action:'SOURCE'},
  {label:'Core architecture',state:'IMPLEMENTED',summary:'Harness, Command Station, Mission Control/WebVM and Factory M2/M3/M4 are represented as implementation claims, not production-qualification claims.',href:'https://github.com/ninja-ops-guy/residual-agent-harness',action:'INSPECT CODE'},
  {label:'Verification boundary',state:'TESTED',summary:'Contracts, receipts, verifier identity, routing boundaries, HITL and integration paths are exercised by automated and adversarial tests.'},
  {label:'Research outcomes',state:'OBSERVED',summary:'Positive and negative experiment outcomes are retained by revision; a later pass does not erase an earlier failure.'},
  {label:'M6 / recursive improvement',state:'OPEN',summary:'Repeated frozen-budget failures remain negative evidence. Recursive self-improvement is explicitly not claimed as solved.'},
  {label:'Production qualification',state:'PENDING',summary:'Blank-environment install, recovery/host-loss, soak, live-provider and device/browser evidence remain release work.'}
];

const box={border:'1px solid #162235',background:'rgba(8,15,28,.78)'};

export default function ProgramCaseStudy({slug}:{slug:string}){
  const p=packets[slug];
  if(!p) return null;
  return <main style={{minHeight:'100vh',background:'#050A14',color:'#E8EDF3'}}><div className="max-w-[1080px] mx-auto px-6 md:px-10" style={{paddingTop:72,paddingBottom:120}}>
    <Link to="/#work" className="font-label" style={{color:'#8899AA'}}>← PORTFOLIO</Link>
    <header style={{marginTop:70}}><p className="font-label" style={{color:'#5A78FF'}}>{p.eyebrow}</p><h1 className="font-headline" style={{fontSize:'clamp(3rem,8vw,6.4rem)',lineHeight:.92,letterSpacing:'-.04em',marginTop:18}}>{p.title}</h1><div className="flex flex-wrap gap-2" style={{marginTop:24}}><span className="font-label" style={{color:'#9AAEFF'}}>● {p.status}</span><span className="font-label" style={{border:'1px solid #334766',padding:'7px 9px',color:'#9AAEFF'}}>{p.state}</span></div><p className="font-body" style={{color:'#A6B3C2',fontSize:20,lineHeight:1.65,maxWidth:850,marginTop:28}}>{p.thesis}</p>{slug==='residual'&&<div className="flex flex-wrap gap-3" style={{marginTop:26}}><EvidenceExplorer title="RESIDUAL / EVIDENCE" items={residualAudit}/><a href="https://github.com/ninja-ops-guy/residual-agent-harness" target="_blank" rel="noreferrer" className="font-label px-5 py-2 border border-[#8899AA] text-[#B7C3D0]">SOURCE →</a></div>}</header>
    <section style={{marginTop:88}}><p className="font-label" style={{color:'#5A78FF'}}>01 / WHAT I WAS TRYING TO SOLVE</p><p className="font-body" style={{fontSize:17,color:'#B7C3D0',lineHeight:1.8,marginTop:18}}>{p.problem}</p></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#5A78FF'}}>02 / RULES I WOULD NOT BREAK</p><div style={{...box,marginTop:22,padding:24}}>{p.constraints.map(x=><p key={x} className="font-body" style={{color:'#A9B6C5',lineHeight:1.7,margin:'8px 0'}}>→ {x}</p>)}</div></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#5A78FF'}}>03 / HOW I BUILT IT</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{marginTop:22}}>{p.architecture.map(x=><div key={x.title} className="p-6" style={box}><h3 className="font-headline" style={{fontSize:22}}>{x.title}</h3><p className="font-body" style={{color:'#9EADBD',lineHeight:1.7,marginTop:12}}>{x.body}</p></div>)}</div></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#5A78FF'}}>04 / WHAT I CAN POINT TO</p><div style={{...box,marginTop:22,padding:26}}>{p.evidence.map((x,i)=><p key={x} className="font-body" style={{color:'#B7C3D0',lineHeight:1.75,borderBottom:i<p.evidence.length-1?'1px solid #162235':undefined,padding:'11px 0'}}>0{i+1} — {x}</p>)}</div></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#5A78FF'}}>05 / HOW I CHECKED IT</p><div style={{marginTop:18}}>{p.verification.map(x=><p key={x} className="font-body" style={{color:'#A6B3C2',lineHeight:1.75,padding:'10px 0',borderBottom:'1px solid #162235'}}>→ {x}</p>)}</div></section>
    <section className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{marginTop:78}}><div className="p-6" style={box}><p className="font-label" style={{color:'#7DE2A8'}}>WHAT I GOT OUT OF IT</p><p className="font-body" style={{color:'#B7C3D0',lineHeight:1.75,marginTop:14}}>{p.result}</p></div><div className="p-6" style={box}><p className="font-label" style={{color:'#D8B26E'}}>WHAT IS STILL OPEN</p><p className="font-body" style={{color:'#B7C3D0',lineHeight:1.75,marginTop:14}}>{p.limitation}</p></div></section>
    <section style={{marginTop:78}}><p className="font-label" style={{color:'#5A78FF'}}>06 / WHAT I CAN REUSE</p><div className="flex flex-wrap gap-2" style={{marginTop:20}}>{p.primitives.map(x=><span key={x} className="font-label" style={{border:'1px solid #263750',padding:'9px 11px',color:'#A9B6C5'}}>{x}</span>)}</div></section>
    {p.integrations&&<section style={{marginTop:78}}><p className="font-label" style={{color:'#5A78FF'}}>07 / WHERE IT CONNECTS</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{marginTop:22}}>{p.integrations.map(x=><div key={x.title} className="p-6" style={box}><h3 className="font-headline" style={{fontSize:22}}>{x.title}</h3><p className="font-body" style={{color:'#9EADBD',lineHeight:1.7,marginTop:12}}>{x.body}</p></div>)}</div></section>}
    {p.roadmap&&<section style={{marginTop:78}}><p className="font-label" style={{color:'#5A78FF'}}>08 / WHERE I AM TAKING IT</p><div style={{...box,marginTop:22,padding:26}}>{p.roadmap.map((x,i)=><p key={x} className="font-body" style={{color:'#B7C3D0',lineHeight:1.75,borderBottom:i<p.roadmap!.length-1?'1px solid #162235':undefined,padding:'11px 0'}}>0{i+1} — {x}</p>)}</div></section>}
    {p.ideas&&<section style={{marginTop:78}}><p className="font-label" style={{color:'#5A78FF'}}>09 / THE IDEAS I THINK MATTER MOST</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{marginTop:22}}>{p.ideas.map(x=><div key={x.title} className="p-6" style={box}><h3 className="font-headline" style={{fontSize:22}}>{x.title}</h3><p className="font-body" style={{color:'#9EADBD',lineHeight:1.7,marginTop:12}}>{x.body}</p></div>)}</div></section>}
    {p.impact&&<section style={{marginTop:78}}><p className="font-label" style={{color:'#7DE2A8'}}>10 / WHY I THINK THIS COULD MATTER</p><div className="p-6" style={{...box,marginTop:22,borderColor:'#244335'}}><p className="font-body" style={{color:'#C5D2DE',fontSize:18,lineHeight:1.8}}>{p.impact}</p></div></section>}
  </div></main>;
}
