const rows = [
  { program:'CIC → RED-TEAM', question:'Can structural properties of SAT and proof search become useful security-analysis mechanisms?', mechanism:'Structural SAT encodings · width/treewidth analysis · necessity/backdoor analysis', reuse:'CTF/red-team harness pnp_lab · verified-planning direction', state:'DIRECT RESEARCH TRANSFER', evidence:'Dedicated CIC modules and test suite in the red-team harness; theoretical, empirical, and open claims kept separate.' },
  { program:'CTF / RED-TEAM HARNESS', question:'Can autonomous security work be bounded, replayed, compared, and observed defensively instead of treated as an opaque agent transcript?', mechanism:'Bounded executors · tamper-evident audit · reasoning replay · evidence graph · specialist router · benchmark runner', reuse:'RESIDUAL adversarial evaluation · agent qualification · security experimentation', state:'PRIVATE / IMPLEMENTED', evidence:'20 challenge scenarios across 12 domains; scripted and LLM solver paths; command isolation; HMAC-chained audit; defensive detection and forensic modules; benchmark and replay machinery.' },
  { program:'VERIFIED CYBER PLANNING', question:'Can generated cyber plans be checked instead of trusted because a planner produced them?', mechanism:'SAT/SMT verification · plan proofs · MUS/counterexamples · policy constraints', reuse:'CTF orchestration · later governed-agent architecture', state:'ENGINEERED + TESTED', evidence:'Verifier generations, automated tests, certificate/proof machinery, explicit rejection and counterexample paths.' },
  { program:'RESIDUAL', question:'Can system-level reliability emerge even when the individual AI workers are stochastic and unreliable?', mechanism:'Frozen contracts · bounded workers · evidence bus · independent verifiers · deterministic integration · obligation DAGs · attestation SDK + adapter conformance', reuse:'Command Station · Factory / Studio · heterogeneous local/cloud execution · LangChain / CrewAI integrations', state:'IMPLEMENTED / RED-TEAM EVALUATION IN PROGRESS', evidence:'Core harness, Command Station, Mission Control/WebVM, and Factory M2/M3/M4 are implemented. The separate residual-sdk issues content-addressed attestations over a hash-chained SQLite backend; LangChain and CrewAI adapters bind real framework lifecycles to the shared conformance suite. Mixed research outcomes are retained rather than collapsed into a success claim; broader reliability remains a controlled-evaluation question.' },
  { program:'LDD-KIT', question:'What changes if observability begins with event contracts instead of being added after implementation?', mechanism:'Event-schema-first logs · traces · metrics · dashboards · alerts · CI validation', reuse:'RESIDUAL mission state · event admission · diagnostics · evidence flow', state:'REUSED PLATFORM PRIMITIVE', evidence:'Reusable multi-language framework with direct integration into a larger autonomous-systems platform.' },
  { program:'RAC / PHYSICAL ROBUSTNESS', question:'Does a digitally promising adversarial design survive governed evaluation and physical testing?', mechanism:'Frozen contracts · held-out separation · provenance · promotion/refusal gates · EOT', reuse:'Research Workbench · physical-AI evidence platform', state:'PHYSICAL VALIDATION PENDING', evidence:'Engineering barriers closed for declared scope; negative digital results retained; P1 software prepared while physical efficacy remains explicitly unestablished.' },
];

export default function EvidenceMatrix(){
  return <section id="evidence" className="relative" style={{background:'#08101D',padding:'110px 0',zIndex:1}}>
    <div className="max-w-[1280px] mx-auto px-6 md:px-10">
      <p className="font-label">RESEARCH IMPACT / EVIDENCE</p>
      <h2 className="font-headline" style={{fontSize:'clamp(2rem,4vw,3.8rem)',color:'#E8EDF3',lineHeight:1.05,marginTop:16,maxWidth:900}}>Question → mechanism → reuse → evidence.</h2>
      <p className="font-body" style={{color:'#8899AA',lineHeight:1.7,maxWidth:900,marginTop:18}}>This is the shortest version of the research portfolio: what I was trying to learn, what I built because of it, where the useful mechanism showed up again, and what evidence I can support today.</p>
      <div style={{marginTop:42,border:'1px solid #1A2540'}}>
        {rows.map((r,i)=><article key={r.program} className="grid grid-cols-1 lg:grid-cols-[0.9fr_1.35fr_1.35fr_1.35fr] gap-px" style={{background:'#1A2540',borderTop:i?'1px solid #1A2540':'none'}}>
          <div style={{background:'#08101D',padding:'22px'}}><div className="font-headline" style={{color:'#E8EDF3',fontSize:16}}>{r.program}</div><div className="font-label" style={{color:'#9AAEFF',marginTop:14,lineHeight:1.5}}>{r.state}</div></div>
          <div style={{background:'#08101D',padding:'22px'}}><div className="font-label" style={{marginBottom:9}}>RESEARCH QUESTION</div><p className="font-body" style={{color:'#B2BECA',fontSize:13,lineHeight:1.65,margin:0}}>{r.question}</p></div>
          <div style={{background:'#08101D',padding:'22px'}}><div className="font-label" style={{marginBottom:9}}>MECHANISM → REUSE</div><p className="font-body" style={{color:'#A0AFBE',fontSize:13,lineHeight:1.65,margin:0}}>{r.mechanism}</p><p className="font-body" style={{color:'#718399',fontSize:12,lineHeight:1.6,marginTop:10}}>Reused in: {r.reuse}</p></div>
          <div style={{background:'#08101D',padding:'22px'}}><div className="font-label" style={{marginBottom:9}}>EVIDENCE / BOUNDARY</div><p className="font-body" style={{color:'#8FA0B2',fontSize:13,lineHeight:1.65,margin:0}}>{r.evidence}</p></div>
        </article>)}
      </div>
      <p className="font-body" style={{color:'#607287',fontSize:12,lineHeight:1.7,marginTop:18}}>The label changes when the evidence changes, not when I get more excited about the project.</p>
    </div>
  </section>
}
